### PR TITLE
Added better pointer handling in GenericValue.

### PR DESCRIPTION
**Pull request by neelance**
Hi,

I just tried out ruby-llvm and got confused, because ExecutionEngine.run_function did not work as expected with pointers as arguments. It took some time to figure it out and I realized that it is a bit difficult to find appropriate method names there. So here is my solution.

Bye,
Richard

### CODE REVIEW

**Comment by jvoorhis** [comment]
This is definitely something to address, but now I wonder if the name from_ptr would be best for your use case. Currently (I hope) the from_ptr class methods are used internally and shouldn't be depended upon by users' code, so this might be an opportunity to simplify. Thanks for getting in touch!

Best,

Jeremy
On Thursday, April 28, 2011 at 3:10 PM, neelance wrote:
Hi,

**Comment by neelance** [comment]
I think the problem when using from_ptr instead of from_value_ptr is, that
it conflicts with to_ptr. And to_ptr is fixed because of FFI. Maybe
from_pointer could be different enough...

2011/4/29 jvoorhis <
reply@reply.github.com>

**Comment by neelance** [comment]
I added some more changes that I need for my JetPEG project. Please take a look at them and pull if you approve them.

**Comment by jvoorhis** [comment]
These changes look good. I've made a couple of subtle API changes to ruby-llvm, and added a ton of docs. After merging these, I think I'll put up another release of ruby-llvm.

You beat me to the punch with JetPEG. You might like Samuel Kamin's paper at http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.52.9376. He outlines a good and simple approach to implementing combinatoric-style DSLs, and in part 3 gives an example for a parser generator that emits C code.

Best,

Jeremy
On Saturday, May 7, 2011 at 9:24 AM, neelance wrote:
I added some more changes that I need for my JetPEG project. Please take a look at them and pull if you approve them.

**Comment by neelance** [comment]
Ah, I just saw your kpeg repository, we seem to have similar interests. ;-)
My process on JetPEG is going quite well, if you take a look at the test
suite you will see that it can already process a lot, and with incredible
speed thanks to ruby-llvm.
I hope to convert this Ruby top-down grammar
http://ruby-tp-dw-gram.rubyforge.org/svn/gram.lisp into a JetPEG grammar
soon.

Btw: I am already using your "next" version of ruby-llvm, that's why the
pull request is for this branch.

**Comment by jvoorhis** [comment]
I went back and forth on to_value_ptr, but this is certainly more useful. Thanks for the good commits!

**Pull request merged**
