### PR TITLE
Finalizers and type system improvements

### PR DESCRIPTION
**Pull request by neelance**
Hi again,

here comes the mentioned pull request with my changes to remove memory leaks. Finalizers are registered to automatically call the appropriate dispose method if an object is garbage collected. I also improved the code for LLVM types a bit.

I hope the changes are okay for you. All tests still pass.

Bye,
Richard

### CODE REVIEW

**Comment by jvoorhis** [comment]
Richard,

Thanks. I like your Type changes, and your fixes for the memory leaks look good too. What's new in JetPEG?

Jeremy

**Comment by neelance** [comment]
Thanks for pulling my commits.

I had stopped working on JetPEG for half a year because of other projects, but now I am back working on it. As you know, I just removed the memory leaks and now I have to tackle a critical performance bug. After that, I can continue to implement new features to finally support my generated Ruby grammar https://github.com/neelance/ruby_grammar_converter/blob/master/ruby.jetpeg . I don't know how long it will take, especially because I have to write my bachelor thesis atm. But my hope remains that one day I can replace the current parser of Rubinius (the grammar: https://github.com/rubinius/rubinius/blob/master/lib/ext/melbourne/grammar18.y) with my pure Ruby+LLVM solution.

Will you push another beta gem to rubygems.org?

Richard

**Comment by evanphx** [comment]
This change introduces a big bug. When an object is dup'd, it's finalizer is also copied over to the new object. But things like the Builder object don't have their own initialize_copy to actually duplicate the underlying data. Thusly, if you dup a Builder (or anything that now has a finalizer), you'll have 2 objects that share the same underlying LLVM data, and when either goes out of scope, the other will basically crash the program when used.

It's this reason I'm highly opposed to using finalizers to cleanup external resources. I think the finalizer change should be reverted rather than introduce a bug that a user can easily hit and not work around.

**Comment by neelance** [comment]
You are right, this is a problem. But at my opinion, relying on the user to clean up resources is also some kind of bug. The user expects objects to be properly garbage collected when they go out of scope. Yes, this library is a binding to a C library, but its goal should be to provide a proper "ruby way" to use the library.
Couldn't we just override dup and disallow cloning? Why should someone need it, since you rightfully stated that we can not really duplicate the LLVM data anyway?

**Comment by evanphx** [comment]
Even if dup is disabled, there is another potential bug: Say you have an llvm Module instance. You create a few functions and then later, you ask the function to return the module that is for. If that request returns a different Module ruby object than the original (which it can since the ruby object is just a wrapper around the C pointer), then when either of those Module objects is GC'd, it breaks the other one.

It is simply too much work and introduces too many random bugs to use finalizers in this way. From the users perspective, a bug that causes a minor memory increase is much better than one that random causes their program to crash.

**Comment by neelance** [comment]
It seems as if you had some bad experiences with finalizers. Has it been proven too error prone in other projects? I think the relations between the objects in LLVM are not so complicated, so my feeling is that one could make it work, maybe adding an additional safety net to avoid segfaults if something goes wrong. But if you say it is a really bad idea, I could replace the finalizers with dispose methods and adapt my JetPEG code. Wouldn't be a big problem, I only thought finalizers would make it easier for others who use this library.

**Comment by evanphx** [comment]
I worked through this a lot when developing FFI in the start. The allure of finalizers to cleanup foreign resources is strong, but it turns into a major issue for your users. Simple patterns they are used to cause random failures that they are unable to work around or understand.

I feel like ruby-llvm needs to be built-proof because it's used as a compiler, something that is both critical and hard for users to grok. The minor additional burden of having the manually disposing (perhaps some blocks that dispose in ensure) is, for me, a better tradeoff.

**Comment by neelance** [comment]
Okay, I trust your experience. I will replace the finalizers with dispose methods and add warnings to the doc comments of the initialize methods. Thanks for your advice.

PS: I think FFI should get some way to automatically raise an exception when nil is passed as a pointer argument. I got LLVM to segfault "horribly" several times during the development of JetPEG because of this simple mistake.

**Comment by evanphx** [comment]
Well, nil == null, which is a totally valid thing to pass for a pointer. I coded it that way on purpose. Perhaps there could be another type, :nonnull_pointer that would raise on nil.

**Comment by neelance** [comment]
Yes, something like that was on my mind.

**Pull request merged**
