### PR TITLE
Replaced finalizers

### PR DESCRIPTION
**Pull request by neelance**
And another pull request because of Evan's concerns in the comments of the previous one.

### CODE REVIEW

**Comment by evanphx** [comment]
This looks good, how about one more little change: When #dispose is called, set @ptr to nil after calling the LLVM function. Also check that @ptr is non-nil at the top of dispose and return early if it is. That way, #dispose can safely be called multiple times.

**Comment by neelance** [comment]
Good idea, I added the changes.

**Comment by evanphx** [comment]
@jvoorhis You cool with this?

**Comment by jvoorhis** [comment]
Hi guys,

I do remember now having this discussion with Evan on IRC. Sticking with the original API is for the best. Evan's point also makes me want to disable cloning some objects altogether, but it hasn't been a problem so far.

Richard: thanks for the fixes and improvements. I feel better about pushing another gem now.

**Pull request merged**
